# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
jobs:
  build:
    machine: true
    image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Echo versions
          command: |
            docker --version
            docker-compose --version
            docker compose --help
      # - run:
      #     name: Update docker and docker compose
      #     command: |
      #       sudo apt-get purge docker-ce containerd.io
      #       curl -fsSL https://get.docker.com -o get-docker.sh
      #       sudo sh get-docker.sh
      #       sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      #       sudo chmod +x /usr/local/bin/docker-compose


# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  test:
    jobs:
      - build
